In [1]:
print ((3 + 1) * 2)
print ((4 + 6) ** 2)
print (((3 + 1) * 2)/ (4 + 6) ** 2)

8
100
0.08


In [2]:
x = 5
y = ((x ** 2) + 1)

print (y)

26


In [5]:
a = 5
b = 10
c = 20
x = -1
y = ( (a * x) ** 2 + (b * x) + c)

print (y)

35


In [8]:
x = 50
x = 3 * x - 50
y = ( (x / x) ** 2 )

print (y)

1.0


# Lists and tuples

In [15]:
x = [10, 8, 20, 6, 30]
print (x [2])

x = (5, 2, 1)
print (x [-1])

x = [(5, 2, 1), (1, 3, 3), (0, -1, -2)]
print ( x [-1])

x = []
x.append (5)
x.append ( (1, 2))
x.append ( [4, 5, 6])
print (x)

20
1
(0, -1, -2)
[5, (1, 2), [4, 5, 6]]


# Packages: math and numpy

In [7]:
import math
from math import sin, cos, pi, e, log
x = sin(pi/2) - cos(pi)
print (x)

x = 3
x = 4
y = ((x ** 2) + (x ** 2)) ** 0.5
print (y)

x = 𝑒 ** log(10)
print (x)

2.0
5.656854249492381
10.000000000000002


In [14]:
import numpy as np
x = np.array( [ 5, 2, 1 ])
print ( x )

x = np.array([
    [ 5, 2, 1 ],
    [ 1, 3, 3 ],
    [ 0, -1, -2]
    ])
print ( x )

x = np.array( [5, 2, 1] )
print ( x+1 )

a = np.array( [ 5, 2, 1 ])
b = np.array( [ 3, -4, 8 ])
print ( a + b )

[5 2 1]
[[ 5  2  1]
 [ 1  3  3]
 [ 0 -1 -2]]
[6 3 2]
[ 8 -2  9]


In [22]:
def myfunction( x ):
  return 2*(x - 1) + 5

print(myfunction(5))

def two_argument_function(a, b):
  return b ** a + 1

print(two_argument_function(3, 2))

def add_vectors(x0, x1):
  x0 = np.array(x0)
  x1 = np.array(x1)
  return x0 + x1

print(add_vectors([1, 2, 3], [4, 5, 6]))

def lastfunction(a, b, c):
  a = np.array(a)
  return b*a + [0, c, 0]

print (lastfunction([1, 0, 2], 5, 10))

13
9
[5 7 9]
[ 5 10 10]
